Repository aws/aws-sdk-kotlin, pull requests merged in 2024-09, with the labels that each got.

#1397 chore: Modified bug issue template to add checkbox to report potential regression.
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/issue-regression-labeler.yml
Labels: no-changelog

#1402 feat: add `@DynamoDbIgnore` and `@DynamoDbItemConverter` annotations
  hll/dynamodb-mapper/dynamodb-mapper-annotations/api/dynamodb-mapper-annotations.api
  hll/dynamodb-mapper/dynamodb-mapper-annotations/common/src/aws/sdk/kotlin/hll/dynamodbmapper/Annotations.kt
  hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/rendering/SchemaRenderer.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPluginTest.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/IgnoredProperty.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/custom-item-converter/CustomItemConverter.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/custom-item-converter/CustomUser.kt
Labels: no-changelog

#1404 fix: stop including playground.js in Dokka pages and correctly filter for internal APIs
  dokka-aws/src/main/kotlin/aws/sdk/kotlin/dokka/AwsDokkaPlugin.kt
  dokka-aws/src/main/kotlin/aws/sdk/kotlin/dokka/transformers/DisablePlaygroundIntegration.kt
  dokka-aws/src/main/kotlin/aws/sdk/kotlin/dokka/transformers/FilterInternalApis.kt
Labels: no-changelog

#1407 misc: bump smithy-kotlin version
  gradle/libs.versions.toml
Labels: no-changelog

#1408 misc: upgrade to kotlinx.coroutines 1.9.0
  .brazil.json
  .changes/36676f86-d1ea-46b6-aa99-2f6c840b5748.json
  build-support/src/main/kotlin/aws/sdk/kotlin/gradle/sdk/tasks/UpdatePackageManifest.kt
  build-support/src/test/kotlin/aws/sdk/kotlin/gradle/sdk/tasks/UpdatePackageManifestTaskTest.kt
  gradle/libs.versions.toml
Labels: acknowledge-artifact-size-increase

#1410 fix: remove `KotlinxCoroutinesCore` transform rule
  .brazil.json
Labels: no-changelog, acknowledge-artifact-size-increase

#1399 feat: basic annotation processing
  hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/AnnotationsProcessor.kt
  hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/rendering/HighLevelRenderer.kt
  hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/rendering/SchemaAttributes.kt
  hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/rendering/SchemaRenderer.kt
  hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/model/MapperTypes.kt
  hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/operations/HighLevelOpsProcessor.kt
  hll/dynamodb-mapper/dynamodb-mapper-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/operations/rendering/OperationRenderer.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/build.gradle.kts
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/plugins/SchemaGeneratorPluginTest.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/standard-item-converters/src/Lists.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/standard-item-converters/src/Maps.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/standard-item-converters/src/Primitives.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/standard-item-converters/src/Sets.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/standard-item-converters/test/ListsTest.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/standard-item-converters/test/MapsTest.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/standard-item-converters/test/PrimitivesTest.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/standard-item-converters/test/SetsTest.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/tests/UserTest.kt
  hll/dynamodb-mapper/dynamodb-mapper/api/dynamodb-mapper.api
  hll/dynamodb-mapper/dynamodb-mapper/common/src/aws/sdk/kotlin/hll/dynamodbmapper/items/DocumentConverter.kt
  hll/dynamodb-mapper/dynamodb-mapper/common/src/aws/sdk/kotlin/hll/dynamodbmapper/items/HeterogeneousItemConverter.kt
  hll/dynamodb-mapper/dynamodb-mapper/common/src/aws/sdk/kotlin/hll/dynamodbmapper/items/ItemConverter.kt
  hll/dynamodb-mapper/dynamodb-mapper/common/src/aws/sdk/kotlin/hll/dynamodbmapper/items/SimpleItemConverter.kt
  hll/dynamodb-mapper/dynamodb-mapper/common/src/aws/sdk/kotlin/hll/dynamodbmapper/values/ItemToValueConverter.kt
  hll/dynamodb-mapper/dynamodb-mapper/common/src/aws/sdk/kotlin/hll/dynamodbmapper/values/scalars/BooleanConverter.kt
  hll/dynamodb-mapper/dynamodb-mapper/common/src/aws/sdk/kotlin/hll/dynamodbmapper/values/scalars/TextConverters.kt
  hll/dynamodb-mapper/dynamodb-mapper/common/src/aws/sdk/kotlin/hll/dynamodbmapper/values/smithytypes/DocumentConverter.kt
  hll/dynamodb-mapper/dynamodb-mapper/common/src/aws/sdk/kotlin/hll/dynamodbmapper/values/smithytypes/InstantConverter.kt
  hll/dynamodb-mapper/dynamodb-mapper/common/test/aws/sdk/kotlin/hll/dynamodbmapper/items/SimpleItemConverterTest.kt
  hll/dynamodb-mapper/dynamodb-mapper/common/test/aws/sdk/kotlin/hll/dynamodbmapper/values/smithytypes/DocumentValueConverterTest.kt
  hll/dynamodb-mapper/dynamodb-mapper/common/test/aws/sdk/kotlin/hll/dynamodbmapper/values/smithytypes/InstantConvertersTest.kt
  hll/dynamodb-mapper/dynamodb-mapper/jvm/test/aws/sdk/kotlin/hll/dynamodbmapper/pipeline/internal/OperationTest.kt
  hll/dynamodb-mapper/tests/dynamodb-mapper-annotation-processor-test/common/test/aws/sdk/kotlin/hll/dynamodbmapper/tests/processor/data/UserTest.kt
  hll/hll-codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/core/CodeGeneratorFactory.kt
  hll/hll-codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/core/TemplateProcessor.kt
  hll/hll-codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/model/Type.kt
  hll/hll-codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/model/Types.kt
  hll/hll-codegen/src/main/kotlin/aws/sdk/kotlin/hll/codegen/util/Pkg.kt
Labels: no-changelog

#1412 misc: add resolve-conflict-dependencies for event streaming
  .brazil.json
Labels: no-changelog

#1388 feat: smoke tests
  .gitignore
  codegen/aws-sdk-codegen/build.gradle.kts
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/GradleGenerator.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/model/traits/testing/SmokeTestTraits.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/smoketests/SmokeTestsCodegenRegionIntegration.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/smoketests/SmokeTestsDenyListIntegration.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/smoketests/testing/SmokeTestFailHttpEngineIntegration.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/smoketests/testing/SmokeTestSuccessHttpEngineIntegration.kt
  codegen/aws-sdk-codegen/src/main/resources/META-INF/services/software.amazon.smithy.kotlin.codegen.integration.KotlinIntegration
  settings.gradle.kts
  tests/codegen/smoke-tests/build.gradle.kts
  tests/codegen/smoke-tests/services/build.gradle.kts
  tests/codegen/smoke-tests/src/test/kotlin/SmokeTestE2ETest.kt
  tests/codegen/smoke-tests/src/test/resources/smoke-tests-failure.smithy
  tests/codegen/smoke-tests/src/test/resources/smoke-tests-success.smithy
Labels: no-changelog

#1420 misc: smithy kotlin version bump
  gradle/libs.versions.toml
Labels: no-changelog

#1421 misc: revert "feat: smoke tests"
  .gitignore
  codegen/aws-sdk-codegen/build.gradle.kts
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/GradleGenerator.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/model/traits/testing/SmokeTestTraits.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/smoketests/SmokeTestsCodegenRegionIntegration.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/smoketests/testing/SmokeTestFailHttpEngineIntegration.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/smoketests/testing/SmokeTestSuccessHttpEngineIntegration.kt
  codegen/aws-sdk-codegen/src/main/resources/META-INF/services/software.amazon.smithy.kotlin.codegen.integration.KotlinIntegration
  settings.gradle.kts
  tests/codegen/smoke-tests/build.gradle.kts
  tests/codegen/smoke-tests/services/build.gradle.kts
  tests/codegen/smoke-tests/src/test/kotlin/SmokeTestE2ETest.kt
  tests/codegen/smoke-tests/src/test/resources/smoke-tests-failure.smithy
  tests/codegen/smoke-tests/src/test/resources/smoke-tests-success.smithy
Labels: no-changelog

#1423 misc: smithy kotlin version bump
  gradle/libs.versions.toml
Labels: no-changelog

#1416 misc: delete unused gradle script
  gradle/init-codeartifact.gradle
Labels: no-changelog
