Repository aws/aws-sdk-kotlin, pull requests merged in 2024-06, with the labels that each got.

#1323 fix: upgrade to latest smithy-kotlin version
  gradle/libs.versions.toml
Labels: no-changelog

#1317 feat: business metrics
  aws-runtime/aws-http/api/aws-http.api
  aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/AwsUserAgentMetadata.kt
  aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/interceptors/BusinessMetricsInterceptor.kt
  aws-runtime/aws-http/common/test/aws/sdk/kotlin/runtime/http/AwsUserAgentMetadataTest.kt
  aws-runtime/aws-http/common/test/aws/sdk/kotlin/runtime/http/interceptors/BusinessMetricsInterceptorTest.kt
  aws-runtime/aws-http/common/test/aws/sdk/kotlin/runtime/http/middleware/UserAgentTest.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/AwsRuntimeTypes.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/BusinessMetricsIntegration.kt
  codegen/aws-sdk-codegen/src/main/resources/META-INF/services/software.amazon.smithy.kotlin.codegen.integration.KotlinIntegration
  gradle/libs.versions.toml
Labels: no-changelog, acknowledge-artifact-size-increase

#1334 fix: revert dynamodb e2e test
  services/dynamodb/e2eTest/src/DynamoDbTestUtils.kt
  services/dynamodb/e2eTest/src/PaginatorTest.kt
Labels: no-changelog, acknowledge-artifact-size-increase

#1333 fix: revert business metrics
  aws-runtime/aws-http/api/aws-http.api
  aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/AwsUserAgentMetadata.kt
  aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/interceptors/BusinessMetricsInterceptor.kt
  aws-runtime/aws-http/common/test/aws/sdk/kotlin/runtime/http/AwsUserAgentMetadataTest.kt
  aws-runtime/aws-http/common/test/aws/sdk/kotlin/runtime/http/interceptors/BusinessMetricsInterceptorTest.kt
  aws-runtime/aws-http/common/test/aws/sdk/kotlin/runtime/http/middleware/UserAgentTest.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/AwsRuntimeTypes.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/BusinessMetricsIntegration.kt
  codegen/aws-sdk-codegen/src/main/resources/META-INF/services/software.amazon.smithy.kotlin.codegen.integration.KotlinIntegration
  gradle/libs.versions.toml
Labels: no-changelog, acknowledge-artifact-size-increase

#1335 feat: support `implicitGlobalRegion`
  aws-runtime/aws-endpoint/api/aws-endpoint.api
  aws-runtime/aws-endpoint/common/src/aws/sdk/kotlin/runtime/endpoint/functions/Functions.kt
  aws-runtime/aws-endpoint/common/test/aws/sdk/kotlin/runtime/endpoint/functions/FunctionsTest.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/endpoints/PartitionsGenerator.kt
  services/build.gradle.kts
  services/s3/e2eTest/src/MutliRegionAccessPointTest.kt
  services/s3/e2eTest/src/S3TestUtils.kt
Labels: no-changelog, acknowledge-api-break

#1338 misc: upgrade to latest version of smithy-kotlin
  aws-runtime/aws-http/api/aws-http.api
  aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/AwsUserAgentMetadata.kt
  aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/interceptors/BusinessMetricsInterceptor.kt
  aws-runtime/aws-http/common/test/aws/sdk/kotlin/runtime/http/AwsUserAgentMetadataTest.kt
  aws-runtime/aws-http/common/test/aws/sdk/kotlin/runtime/http/interceptors/BusinessMetricsInterceptorTest.kt
  aws-runtime/aws-http/common/test/aws/sdk/kotlin/runtime/http/middleware/UserAgentTest.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/AwsRuntimeTypes.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/BusinessMetricsIntegration.kt
  codegen/aws-sdk-codegen/src/main/resources/META-INF/services/software.amazon.smithy.kotlin.codegen.integration.KotlinIntegration
  gradle/libs.versions.toml
  services/dynamodb/e2eTest/src/DynamoDbTestUtils.kt
  services/dynamodb/e2eTest/src/PaginatorTest.kt
Labels: no-changelog, acknowledge-artifact-size-increase

#1342 fix: flaky test `testAsyncRefreshHandlesFailures`
  services/s3/common/test/aws/sdk/kotlin/services/s3/express/DefaultS3ExpressCredentialsProviderTest.kt
Labels: no-changelog
