Repository aws/aws-sdk-kotlin, pull requests merged in 2024-04, with the labels that each got.

#1269 chore: update smithy-kotlin repo paths
  .github/actions/setup-build/action.yml
  .github/workflows/codegen-preview.yml
Labels: no-changelog

#1270 misc: replace Snyk with GitHub Dependabot
  .github/workflows/dependabot.yml
  .github/workflows/snyk-scan.yml
Labels: no-changelog

#1271 misc: bump versions
  gradle/libs.versions.toml
Labels: no-changelog

#1275 misc: model sync
  codegen/sdk/aws-models/application-insights.json
  codegen/sdk/aws-models/codestar-notifications.json
  codegen/sdk/aws-models/controlcatalog.json
  codegen/sdk/aws-models/elastic-beanstalk.json
  codegen/sdk/aws-models/elastic-load-balancing.json
  codegen/sdk/aws-models/launch-wizard.json
  codegen/sdk/aws-models/m2.json
  codegen/sdk/aws-models/mgn.json
  codegen/sdk/aws-models/neptune.json
  codegen/sdk/aws-models/neptunedata.json
  codegen/sdk/aws-models/network-firewall.json
  codegen/sdk/aws-models/networkmonitor.json
  codegen/sdk/aws-models/opensearchserverless.json
  codegen/sdk/aws-models/s3outposts.json
  codegen/sdk/aws-models/sso-oidc.json
  codegen/sdk/aws-models/sts.json
  codegen/sdk/aws-models/support.json
  codegen/sdk/aws-models/translate.json
Labels: no-changelog

#1277 misc: bump to 1.1.15-SNAPSHOT
  gradle.properties
Labels: no-changelog

#1279 fix: remove `bootstrapAll` task from service benchmarks project; move project inclusion logic to root settings.gradle.kts
  settings.gradle.kts
  tests/benchmarks/service-benchmarks/build.gradle.kts
Labels: no-changelog

#1284 fix: apply clock skew interceptor to clients created via `invoke`
  .changes/f164451a-1adc-4220-9a7d-1765959c23d3.json
  aws-runtime/aws-config/api/aws-config.api
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactory.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/AwsServiceConfigIntegration.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/ServiceClientCompanionObjectWriter.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/AccountIdEndpointBuiltinCustomization.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/ClientConfigIntegration.kt
  codegen/aws-sdk-codegen/src/test/kotlin/aws/sdk/kotlin/codegen/ServiceClientCompanionObjectWriterTest.kt
  gradle/libs.versions.toml
Labels: acknowledge-api-break

#1297 misc!: v1.2.0
  .changes/811e504c-89f0-44e3-8216-5024ce6657ac.json
  .changes/f164451a-1adc-4220-9a7d-1765959c23d3.json
  aws-runtime/aws-config/api/aws-config.api
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactory.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/AwsServiceConfigIntegration.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/ServiceClientCompanionObjectWriter.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/AccountIdEndpointBuiltinCustomization.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/ClientConfigIntegration.kt
  codegen/aws-sdk-codegen/src/test/kotlin/aws/sdk/kotlin/codegen/ServiceClientCompanionObjectWriterTest.kt
  gradle/libs.versions.toml
Labels: acknowledge-api-break

#1290 feat: artifact size metrics
  .github/actions/setup-build/action.yml
  .github/scripts/run-codebuild-batch-job.sh
  .github/workflows/codebuild-ci.yml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: no-changelog, acknowledge-artifact-size-increase
