Repository aws/aws-sdk-kotlin, pull requests merged in 2025-05, with the labels that each got.

#1591 fix: support for schema codegen of nullable list / map elements
  .changes/26842b1e-eda3-4dc5-b306-20cce3a1125d.json
  hll/dynamodb-mapper/dynamodb-mapper-schema-codegen/src/main/kotlin/aws/sdk/kotlin/hll/dynamodbmapper/codegen/annotations/rendering/SchemaRenderer.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/standard-item-converters/src/Lists.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/standard-item-converters/src/Maps.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/standard-item-converters/src/Sets.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/standard-item-converters/test/ListsTest.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/standard-item-converters/test/MapsTest.kt
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/src/test/resources/standard-item-converters/test/SetsTest.kt
Labels: dynamodb-mapper

#1587 feat: add analytics to api ref docs
  docs/dokka-presets/templates/base.ftl
  dokka-aws/build.gradle.kts
  dokka-aws/src/test/kotlin/aws/sdk/kotlin/dokka/DokkaAwsTest.kt
  gradle/libs.versions.toml
Labels: no-changelog

#1589 misc: adapt codebuild ci for alternative repos
  .github/scripts/run-codebuild-batch-job.sh
Labels: no-changelog, acknowledge-artifact-size-increase

#1593 misc: enable disabled kotlin native tests
  aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/auth/credentials/EcsCredentialsProviderTest.kt
  aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/region/DefaultRegionProviderChainTest.kt
  aws-runtime/aws-config/jvm/test/aws/sdk/kotlin/runtime/region/DefaultRegionProviderChainTestJVM.kt
  aws-runtime/aws-config/native/src/aws/sdk/kotlin/runtime/auth/credentials/executeCommandNative.kt
  build.gradle.kts
Labels: no-changelog, acknowledge-artifact-size-increase

#1600 misc: add release readiness to contributing.md
  .github/workflows/release-readiness.yml
  CONTRIBUTING.md
Labels: no-changelog, ready-for-release
