Repository aws/aws-sdk-kotlin, pull requests merged in 2025-07, with the labels that each got.

#1635 chore: bump aws-kotlin-repo-tools version
  gradle/libs.versions.toml
Labels: no-changelog, ready-for-release

#1643 chore: add missing permissions for GitHub workflows
  .github/workflows/api-compat-verification.yml
  .github/workflows/closed-issue-message.yaml
  .github/workflows/continuous-integration.yml
  .github/workflows/issue-regression-labeler.yml
  .github/workflows/lint.yml
  .github/workflows/merge-main.yml
  .github/workflows/release-readiness.yml
  .github/workflows/stale_issue.yaml
  .github/workflows/sync-mirror.yml
Labels: no-changelog

#1650 kn: depend on SNAPSHOT version of smithy-kotlin
  gradle/libs.versions.toml
Labels: no-changelog, acknowledge-artifact-size-increase

#1651 chore: v1.5-main sync from main
  .changes/05ac561b-963f-4953-bb4f-1fc19fc1207c.json
  .changes/49af01b8-6fed-4add-ace0-9f027e83425a.json
  .changes/929f0e2a-3af9-4f73-9f1b-b4e97f91f0db.json
  .changes/e6515649-dab5-4be9-b4b4-b289369960d5.json
  .changes/f56de67b-6779-4296-a7d0-dcdefa0d4acd.json
  .github/workflows/merge-main.yml
  .github/workflows/sync-mirror.yml
  aws-runtime/aws-config/api/aws-config.api
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/EcsCredentialsProvider.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/auth/credentials/JsonCredentialsDeserializer.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactory.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AwsSdkClientConfig.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AwsSdkSetting.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/endpoints/Resolvers.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/imds/ImdsClient.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/imds/ImdsResolvers.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsProfile.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/region/DefaultRegionProviderChain.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/region/EnvironmentRegionProvider.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/region/ImdsRegionProvider.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/region/ProfileRegionProvider.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/region/RegionProvider.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/region/RegionProviderChain.kt
  aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/config/endpoints/ResolveEndpointDiscoveryTest.kt
  aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/region/AwsRegionProviderChainTest.kt
  aws-runtime/aws-config/jvm/src/aws/sdk/kotlin/runtime/region/DefaultRegionProviderChainJVM.kt
  aws-runtime/aws-config/jvm/src/aws/sdk/kotlin/runtime/region/JvmSystemPropRegionProvider.kt
  aws-runtime/aws-config/jvm/test/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactoryTest.kt
  aws-runtime/aws-config/native/src/aws/sdk/kotlin/runtime/region/DefaultRegionProviderChainNative.kt
  aws-runtime/aws-core/api/aws-core.api
  aws-runtime/aws-endpoint/api/aws-endpoint.api
  aws-runtime/aws-endpoint/common/src/aws/sdk/kotlin/runtime/endpoint/functions/Functions.kt
  aws-runtime/aws-http/api/aws-http.api
  aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/interceptors/UnsupportedSigningAlgorithmInterceptor.kt
  aws-runtime/aws-http/common/test/aws/sdk/kotlin/runtime/http/interceptors/UnsupportedSigningAlgorithmInterceptorTest.kt
  aws-runtime/aws-http/common/test/aws/sdk/kotlin/runtime/http/middleware/AwsRetryHeaderMiddlewareTest.kt
  aws-runtime/aws-http/common/test/aws/sdk/kotlin/runtime/http/middleware/RecursionDetectionTest.kt
  aws-runtime/aws-http/common/test/aws/sdk/kotlin/runtime/http/middleware/UserAgentTest.kt
  aws-runtime/build.gradle.kts
  bom/build.gradle.kts
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/AwsRuntimeTypes.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/AwsServiceConfigIntegration.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/PresignerGenerator.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/ReplaceServiceExceptionBase.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/polly/PollyPresigner.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/endpoints/AwsEndpointDiscoveryIntegration.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/endpoints/BindAwsEndpointBuiltins.kt
  codegen/aws-sdk-codegen/src/main/resources/META-INF/services/software.amazon.smithy.kotlin.codegen.integration.KotlinIntegration
  codegen/aws-sdk-codegen/src/test/kotlin/aws/sdk/kotlin/codegen/AwsServiceConfigIntegrationTest.kt
  docs/targets.md
  gradle.properties
  gradle/libs.versions.toml
  hll/build.gradle.kts
  hll/dynamodb-mapper/dynamodb-mapper-schema-generator-plugin/api/dynamodb-mapper-schema-generator-plugin.api
  hll/dynamodb-mapper/dynamodb-mapper/api/dynamodb-mapper.api
  tests/benchmarks/service-benchmarks/build.gradle.kts
Labels: acknowledge-api-break, acknowledge-artifact-size-increase

#1646 feat: migrate to jreleaser
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
Labels: no-changelog

#1655 misc: repo tools v0.4.35
  gradle/libs.versions.toml
Labels: no-changelog
