Repository aws/aws-sdk-kotlin, pull requests merged in 2025-01, with the labels that each got.

#1483 fix: change ddb local stop location
  hll/dynamodb-mapper/dynamodb-mapper/build.gradle.kts
Labels: no-changelog

#1494 chore: add *-main to branch workflows
  .github/workflows/api-compat-verification.yml
  .github/workflows/changelog-verification.yml
  .github/workflows/codebuild-ci.yml
  .github/workflows/dependabot.yml
  .github/workflows/kat-transform.yml
  .github/workflows/lint.yml
Labels: no-changelog

#1493 chore: add .kotlin/ to .gitignore
  .gitignore
Labels: no-changelog

#1496 chore: smithy version bump
  gradle/libs.versions.toml
Labels: no-changelog

#1501 fix: profile credentials provider test
  aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/auth/credentials/ProfileCredentialsProviderTest.kt
  aws-runtime/aws-config/jvm/test/aws/sdk/kotlin/runtime/auth/credentials/ProfileCredentialsProviderTestJVM.kt
Labels: no-changelog

#1475 feat: support default checksums
  .changes/3339e5cc-978c-4941-a975-6c0c82d6426f.json
  .github/workflows/continuous-integration.yml
  aws-runtime/aws-config/api/aws-config.api
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactory.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AwsSdkSetting.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/checksums/ResolveFlexibleChecksumsConfig.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsProfile.kt
  aws-runtime/aws-http/api/aws-http.api
  aws-runtime/aws-http/common/src/aws/sdk/kotlin/runtime/http/interceptors/IgnoreCompositeFlexibleChecksumResponseInterceptor.kt
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  buildSrc/src/main/kotlin/aws/sdk/kotlin/tests/codegen/CodegenTest.kt
  codegen/aws-sdk-codegen/build.gradle.kts
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/AwsRuntimeTypes.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/PresignerGenerator.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/flexiblechecksums/FlexibleChecksumsRequest.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/flexiblechecksums/FlexibleChecksumsResponse.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/express/S3ExpressIntegration.kt
  services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressCrc32ChecksumInterceptor.kt
  services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressDefaultChecksumAlgorithm.kt
  services/s3/common/src/aws/sdk/kotlin/services/s3/express/S3ExpressDisableChecksumInterceptor.kt
  services/s3/e2eTest/src/PaginatorTest.kt
  services/s3/e2eTest/src/S3ChecksumTest.kt
  services/s3/e2eTest/src/S3ExpressTest.kt
  services/s3/e2eTest/src/S3IntegrationTest.kt
  services/s3/e2eTest/src/S3TestUtils.kt
  settings.gradle.kts
  tests/codegen/build.gradle.kts
  tests/codegen/checksums/build.gradle.kts
  tests/codegen/checksums/src/test/kotlin/aws/sdk/kotlin/tests/codegen/checksums/ChecksumBusinessMetricsTest.kt
  tests/codegen/checksums/src/test/kotlin/aws/sdk/kotlin/tests/codegen/checksums/ChecksumConfigTest.kt
  tests/codegen/checksums/src/test/kotlin/aws/sdk/kotlin/tests/codegen/checksums/ChecksumRequestTest.kt
  tests/codegen/checksums/src/test/kotlin/aws/sdk/kotlin/tests/codegen/checksums/ChecksumResponseTest.kt
  tests/codegen/checksums/src/test/kotlin/aws/sdk/kotlin/tests/codegen/checksums/utils/ChecksumTestUtils.kt
  tests/codegen/checksums/src/test/resources/checksums.smithy
  tests/codegen/event-stream/build.gradle.kts
  tests/codegen/event-stream/src/test/kotlin/aws/sdk/kotlin/tests/codegen/eventstream/HttpEventStreamTests.kt
  tests/codegen/event-stream/src/test/kotlin/aws/sdk/kotlin/tests/codegen/eventstream/RpcEventStreamTests.kt
  tests/codegen/event-stream/src/test/resources/event-stream-initial-request-response.smithy
  tests/codegen/event-stream/src/test/resources/event-stream-model-template.smithy
  tests/codegen/rules-engine/build.gradle.kts
  tests/codegen/rules-engine/src/test/resources/operation-context-params.smithy
  tests/codegen/smoke-tests/build.gradle.kts
  tests/codegen/smoke-tests/services/build.gradle.kts
  tests/codegen/smoke-tests/src/test/kotlin/aws/sdk/kotlin/test/codegen/smoketest/SmokeTestE2ETest.kt
Labels: acknowledge-artifact-size-increase

#1513 fix: correct broken s3tables model
  codegen/sdk/aws-models/s3tables.json
Labels: no-changelog, acknowledge-artifact-size-increase

#1512 fix: upgrade smithy-kotlin to pick up fixes for header signing
  .changes/9922940a-efce-4e11-b953-f55c6feb4aef.json
  gradle/libs.versions.toml
Labels: acknowledge-artifact-size-increase

#1514 chore: add documentation showing how to configure a custom MD5 checksum interceptor for S3
  docs/howto/s3/md5-checksum-interceptor.md
Labels: no-changelog, acknowledge-artifact-size-increase

#1515 fix: enhance smoke test debuggability by adding `--stacktrace` flag to inner Gradle runner
  tests/codegen/smoke-tests/src/test/kotlin/aws/sdk/kotlin/test/codegen/smoketest/SmokeTestE2ETest.kt
Labels: no-changelog, acknowledge-artifact-size-increase

#1507 misc: awsprofile enum parser
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/profile/AwsProfile.kt
Labels: no-changelog
