Repository aws/aws-sdk-kotlin, pull requests merged in 2025-10, with the labels that each got.

#1699 misc: smithy-kotlin version bump
  gradle/libs.versions.toml
Labels: no-changelog

#1700 chore: bump smithy version
  gradle/libs.versions.toml
Labels: no-changelog, acknowledge-artifact-size-increase

#1702 misc: add Sonatype publishing task configuration
  aws-runtime/build.gradle.kts
  bom/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
  hll/build.gradle.kts
  services/build.gradle.kts
Labels: no-changelog, acknowledge-artifact-size-increase, ready-for-release

#1705 revert "misc: revert sonatype change (#1704)"
  aws-runtime/build.gradle.kts
  bom/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
  hll/build.gradle.kts
  services/build.gradle.kts
Labels: no-changelog
