Repository aws/aws-sdk-kotlin, pull requests merged in 2025-02, with the labels that each got.

#1519 fix: enhance smoke test debuggability by echoing build output from inner Gradle runner
  tests/codegen/smoke-tests/src/test/kotlin/aws/sdk/kotlin/test/codegen/smoketest/SmokeTestE2ETest.kt
Labels: no-changelog

#1488 feat: provide client config property for region provider
  .changes/05ac561b-963f-4953-bb4f-1fc19fc1207c.json
  aws-runtime/aws-config/api/aws-config.api
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactory.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/config/AwsSdkClientConfig.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/region/DefaultRegionProviderChain.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/region/EnvironmentRegionProvider.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/region/ImdsRegionProvider.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/region/ProfileRegionProvider.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/region/RegionProvider.kt
  aws-runtime/aws-config/common/src/aws/sdk/kotlin/runtime/region/RegionProviderChain.kt
  aws-runtime/aws-config/common/test/aws/sdk/kotlin/runtime/region/AwsRegionProviderChainTest.kt
  aws-runtime/aws-config/jvm/src/aws/sdk/kotlin/runtime/region/DefaultRegionProviderChainJVM.kt
  aws-runtime/aws-config/jvm/src/aws/sdk/kotlin/runtime/region/JvmSystemPropRegionProvider.kt
  aws-runtime/aws-config/jvm/test/aws/sdk/kotlin/runtime/config/AbstractAwsSdkClientFactoryTest.kt
  aws-runtime/aws-config/native/src/aws/sdk/kotlin/runtime/region/DefaultRegionProviderChainNative.kt
  aws-runtime/aws-core/api/aws-core.api
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/AwsRuntimeTypes.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/AwsServiceConfigIntegration.kt
  codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/endpoints/BindAwsEndpointBuiltins.kt
  codegen/aws-sdk-codegen/src/test/kotlin/aws/sdk/kotlin/codegen/AwsServiceConfigIntegrationTest.kt
  gradle/libs.versions.toml
Labels: acknowledge-api-break

#1486 misc: gradle mirror
  .github/workflows/codebuild-ci.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/kat-transform.yml
  .github/workflows/lint.yml
  .github/workflows/update-release-branch.yml
  examples/gradle/wrapper/gradle-wrapper.properties
  gradle/wrapper/gradle-wrapper.properties
  tests/integration-tests/ecs-credentials/gradle/wrapper/gradle-wrapper.properties
Labels: no-changelog

#1525 misc: bump build plugin version
  gradle/libs.versions.toml
Labels: no-changelog

#1509 chore: removing unused ECS container credentials integration test
  tests/integration-tests/ecs-credentials/.gitattributes
  tests/integration-tests/ecs-credentials/.gitignore
  tests/integration-tests/ecs-credentials/.npmignore
  tests/integration-tests/ecs-credentials/README.md
  tests/integration-tests/ecs-credentials/app/Dockerfile
  tests/integration-tests/ecs-credentials/app/build.gradle.kts
  tests/integration-tests/ecs-credentials/app/gradle.properties
  tests/integration-tests/ecs-credentials/app/src/main/kotlin/aws/sdk/kotlin/test/Main.kt
  tests/integration-tests/ecs-credentials/bin/ecs-credentials.ts
  tests/integration-tests/ecs-credentials/cdk.json
  tests/integration-tests/ecs-credentials/gradle/wrapper/gradle-wrapper.jar
  tests/integration-tests/ecs-credentials/gradle/wrapper/gradle-wrapper.properties
  tests/integration-tests/ecs-credentials/gradlew
  tests/integration-tests/ecs-credentials/gradlew.bat
  tests/integration-tests/ecs-credentials/jest.config.js
  tests/integration-tests/ecs-credentials/lib/ecs-credentials-stack.ts
  tests/integration-tests/ecs-credentials/package-lock.json
  tests/integration-tests/ecs-credentials/package.json
  tests/integration-tests/ecs-credentials/settings.gradle.kts
  tests/integration-tests/ecs-credentials/tsconfig.json
Labels: no-changelog, acknowledge-artifact-size-increase

#1523 misc: gradle version bump
  gradle/wrapper/gradle-wrapper.properties
Labels: no-changelog, acknowledge-artifact-size-increase

#1530 fix: update-release-branch workflow having Gradle URL code changes
  .github/workflows/update-release-branch.yml
Labels: no-changelog

#1531 misc: fix main to release merge conflicts
  gradle/wrapper/gradle-wrapper.properties
Labels: no-changelog

#1539 misc: bump smithy-kotlin version
  gradle/libs.versions.toml
Labels: no-changelog

#1541 misc: smithy-kotlin version bump
  gradle/libs.versions.toml
Labels: no-changelog

#1540 misc: make route 53 uri tests resilient to model version changes
  services/build.gradle.kts
  services/route53/e2eTest/src/Route53UriTest.kt
  services/route53/model/route53-tests.smithy
Labels: no-changelog
